# Main Docker Compose for local development (all services)

version: '3.8'

services:
  orderservice:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/orders_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: none # Liquibase handles schema
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/db.changelog-master.yaml
    depends_on:
      - postgres_db
    networks:
      - coffee_shop_network

  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coffee_shop_network

volumes:
  postgres_data:

networks:
  coffee_shop_network:
    driver: bridge